name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]    # ci 파이프라인이 다 작동되면 cd 파이프라인 실행하겠다.
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f dweb
      
      - name: Pull Docker Image from Docker hub
        run: sudo docker pull dweblab/songdo:latest
      
      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name dweb dweblab/songdo:latest
