name: CI Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest    # 우분투 latest가 설치된 vm에서 밑의 step을 실시. 총 8개의 rule을 실행
    steps:
      - uses: actions/checkout@v4   # uses는 깃헙 마켓플레이스에서 남이 쓴 것을 사용한다는 의미임
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      
      - run: npm ci
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub         # 도커허브에 로그인해라
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 시크릿 키
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t dawonkim/songdo .
      
      - name: Push docker image
        run: docker push dawonkim/songdo:latest
